mohiva/play-silhouette

app/com/mohiva/play/silhouette/api/Authenticator.scala
app/com/mohiva/play/silhouette/api/Silhouette.scala
app/com/mohiva/play/silhouette/api/services/AuthenticatorService.scala
app/com/mohiva/play/silhouette/impl/authenticators/BearerTokenAuthenticator.scala
app/com/mohiva/play/silhouette/impl/authenticators/CookieAuthenticator.scala
app/com/mohiva/play/silhouette/impl/authenticators/DummyAuthenticator.scala
app/com/mohiva/play/silhouette/impl/authenticators/JWTAuthenticator.scala
app/com/mohiva/play/silhouette/impl/authenticators/SessionAuthenticator.scala
app/com/mohiva/play/silhouette/test/package.scala
docs/how-it-works/authenticator.rst
test/com/mohiva/play/silhouette/api/SilhouetteSpec.scala
test/com/mohiva/play/silhouette/impl/authenticators/BearerTokenAuthenticatorSpec.scala
test/com/mohiva/play/silhouette/impl/authenticators/CookieAuthenticatorSpec.scala
test/com/mohiva/play/silhouette/impl/authenticators/DummyAuthenticatorSpec.scala
test/com/mohiva/play/silhouette/impl/authenticators/JWTAuthenticatorSpec.scala
test/com/mohiva/play/silhouette/impl/authenticators/SessionAuthenticatorSpec.scala

Based on this [SO question](http://stackoverflow.com/questions/27417061/reaching-jwt-token-in-play2-silhouette-jwtauthenticator) it would be nice if the authenticator could return the generated value instead of embedding it into the the response or request.
The JWT authenticator should then return a string representing the generated JWT, the cookie authenticator should return a `Cookie` instance, the session authenticator a `Session` instance and so on.

Add new init method which returns the generated value instead of embedding it 

---

app/com/mohiva/play/silhouette/impl/providers/OAuth1Provider.scala
app/com/mohiva/play/silhouette/impl/providers/oauth1/LinkedInProvider.scala
app/com/mohiva/play/silhouette/impl/providers/oauth1/TwitterProvider.scala
app/com/mohiva/play/silhouette/impl/providers/oauth1/XingProvider.scala
app/com/mohiva/play/silhouette/impl/providers/oauth1/services/PlayOAuth1Service.scala
test/com/mohiva/play/silhouette/impl/providers/OAuth1ProviderSpec.scala
test/com/mohiva/play/silhouette/impl/providers/oauth1/LinkedInProviderSpec.scala
test/com/mohiva/play/silhouette/impl/providers/oauth1/TwitterProviderSpec.scala
test/com/mohiva/play/silhouette/impl/providers/oauth1/XingProviderSpec.scala
test/com/mohiva/play/silhouette/impl/providers/oauth1/services/PlayOAuth1ServiceSpec.scala

The old code has implemented a fix for the [session fixation attack](http://oauth.net/advisories/2009-1/) discovered in 2009. The [fix](http://hueniverse.com/2009/04/23/explaining-the-oauth-session-fixation-attack/) was to check that the user who starts the process is the same as the one who finishes it. In SecureSocial this was implemented with a cache -> session combination, and Silhouette has inherited it from the SecureSocial code base.
This isn't longer needed because the 1.0a specification introduced the additional `oauth_verifier` parameter which was already implemented in the SecureSocial code base. Therefore the current code doesn't work already with the 1.0 specification, because of the `oauth_verifier` parameter which is mandatory for retrieving a access token.
So this pull …

Force OAuth1 provider to use the safer 1.0a specification and remove cache dependency

---

CHANGELOG.md
app/com/mohiva/play/silhouette/impl/providers/SocialProvider.scala
app/com/mohiva/play/silhouette/impl/providers/oauth1/LinkedInProvider.scala
app/com/mohiva/play/silhouette/impl/providers/oauth1/TwitterProvider.scala
app/com/mohiva/play/silhouette/impl/providers/oauth1/XingProvider.scala
app/com/mohiva/play/silhouette/impl/providers/oauth2/DropboxProvider.scala
app/com/mohiva/play/silhouette/impl/providers/oauth2/FacebookProvider.scala
app/com/mohiva/play/silhouette/impl/providers/oauth2/FoursquareProvider.scala
app/com/mohiva/play/silhouette/impl/providers/oauth2/GitHubProvider.scala
app/com/mohiva/play/silhouette/impl/providers/oauth2/GoogleProvider.scala
app/com/mohiva/play/silhouette/impl/providers/oauth2/InstagramProvider.scala
app/com/mohiva/play/silhouette/impl/providers/oauth2/LinkedInProvider.scala
app/com/mohiva/play/silhouette/impl/providers/oauth2/VKProvider.scala
docs/how-it-works/providers.rst
test/com/mohiva/play/silhouette/impl/providers/custom/FacebookProviderSpec.scala

The social profile builder in the old implementation has defined the default parser to return a `CommonSocialProfile` instance instead of the `Profile` type defined as `type Profile <: SocialProfile`. So it wasn't possible to write a parser which returns a custom social profile.
The new implementation can now handle this. It provides now a profile parser which can handle custom social profiles and which can be reused by other profile parsers to avoid code duplication.

Better social profile builder implementation

---

docs/how-it-works/authenticator.rst
docs/how-it-works/providers.rst

These are missing links which refer to source tree instead of a blob.

Fix hyperlinks to source trees

---

silhouette/app/com/mohiva/play/silhouette/impl/util/DefaultFingerprintGenerator.scala
silhouette/test/com/mohiva/play/silhouette/impl/util/DefaultFingerprintGeneratorSpec.scala

Replace `Accept` header with `Accept-Language`, `Accept-Charset` and `Accept-Encoding` headers in default fingerprint generator

---

docs/how-it-works/error-handling.rst

Unless I'm misunderstanding https://github.com/mohiva/play-silhouette/blob/ce877f/docs/how-it-works/error-handling.rst
> The AccessDeniedException will be thrown if a user provides incorrect credentials
The following lines should throw AccessDeniedExceptions instead of AuthenticationExceptions:
[CredentialsProvider.scala#L76](https://github.com/mohiva/play-silhouette/blob/ce877f/silhouette/app/com/mohiva/play/silhouette/impl/providers/CredentialsProvider.scala#L76)
[BasicAuthProvider.scala#L77](https://github.com/mohiva/play-silhouette/blob/ce877f/silhouette/app/com/mohiva/play/silhouette/impl/providers/BasicAuthProvider.scala#L77)

CredentialsProvider & BasicAuthProvider should throw AccessDeniedExceptions

---

docs/configuration.rst
silhouette/app/com/mohiva/play/silhouette/impl/providers/OAuth2Provider.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/OAuth2ProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/custom/FacebookProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth2/ClefProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth2/DropboxProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth2/FacebookProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth2/FoursquareProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth2/GitHubProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth2/GoogleProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth2/InstagramProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth2/LinkedInProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth2/VKProviderSpec.scala

For client side authentication frameworks like Satellizer or Clef the step to get the authorization code isn't necessary because this will be handled by this client side frameworks. So the `authorizationURL` should be optional in this case.

Make `authorizationURL` for OAuth2 provider optional

---

silhouette-testkit/app/com/mohiva/play/silhouette/test/Fakes.scala

When the `encryptSubject` configuration is activated, the encryption rely on `Crypto.encryptAES` which require a started application (https://github.com/playframework/playframework/blob/2.3.x/framework/src/play/src/main/scala/play/api/libs/Crypto.scala#L59).
By just setting encryptSubject to false in test, it should allows to initiate the JWSAuthenticator before the WithApplication block.

Make FakeJWTAuthenticatorService working without started app

---

silhouette/app/com/mohiva/play/silhouette/impl/authenticators/SessionAuthenticator.scala
silhouette/test/com/mohiva/play/silhouette/impl/authenticators/SessionAuthenticatorSpec.scala

Hi,
We currently have the problem that if we use the SessionAuthenticator as authenticator we cannot add additional values in the Session anymore. These values will be removed during the update/touch process of the sessionauthenticator.
```java
package com.springer.nemo.identity.controllers
import com.mohiva.play.silhouette.api
import com.mohiva.play.silhouette.api.{ LoginInfo, Silhouette }
import com.mohiva.play.silhouette.impl.authenticators.SessionAuthenticator
import com.mohiva.play.silhouette.test.{ FakeEnvironment, FakeRequestWithAuthenticator }
import org.scalatest.{ Matchers, FlatSpec }
import org.scalatest.concurrent.{ AsyncAssertions, ScalaFutures }
import play.api.Play
import play.api.test.{ FakeApplication, FakeRequest }
import play.api.test.Helpers._
case class …
```

Sessionauthenticator removes added Values from Play Session

---

docs/how-it-works/identity.rst

I found a small typo in a code sample from documentation: there is an extra comma at the end of line no 41

Fix typo in a code sample

---

silhouette/app/com/mohiva/play/silhouette/impl/providers/OAuth1Provider.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/OAuth2Provider.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/OpenIDProvider.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/SocialProvider.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/openid/services/PlayOpenIDService.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/OAuth1ProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/OAuth2ProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/OpenIDProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth1/LinkedInProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth1/TwitterProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth1/XingProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/openid/SteamProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/openid/YahooProviderSpec.scala

Please excuse this incomplete PR, its only meant to start a discussion.  I was wondering if you would be open to the idea of allowing relative callback urls in OAuth1, OAuth2 & OpenID settings?  I figure that
- the urls should be configured using play's reverse routes
- the only thing that changes between environments is the domain
- in almost all cases, the domain that starts the oauth flow is the one that will get the redirect from the 3rd party provider
- having less duplication in the conf files is a good thing
Expected usage:
```scala
def provideFacebookProvider(httpLayer: HTTPLayer, stateProvider: OAuth2StateProvider): FacebookProvider = {
FacebookProvider(httpLayer, stateProvider, OAuth2Settings(
//...
redirectURL = routes.SocialAuthController.authenticate("facebook").toString …
```

Relative callback urls?

---

silhouette/app/com/mohiva/play/silhouette/api/Silhouette.scala
silhouette/app/com/mohiva/play/silhouette/api/services/AuthenticatorService.scala
silhouette/app/com/mohiva/play/silhouette/impl/authenticators/BearerTokenAuthenticator.scala
silhouette/app/com/mohiva/play/silhouette/impl/authenticators/CookieAuthenticator.scala
silhouette/app/com/mohiva/play/silhouette/impl/authenticators/DummyAuthenticator.scala
silhouette/app/com/mohiva/play/silhouette/impl/authenticators/JWTAuthenticator.scala
silhouette/app/com/mohiva/play/silhouette/impl/authenticators/SessionAuthenticator.scala
silhouette/test/com/mohiva/play/silhouette/api/SilhouetteSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/authenticators/BearerTokenAuthenticatorSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/authenticators/CookieAuthenticatorSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/authenticators/DummyAuthenticatorSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/authenticators/JWTAuthenticatorSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/authenticators/SessionAuthenticatorSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth1/secrets/CookieSecretSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth2/state/CookieStateSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth2/state/DummyStateSpec.scala

This PR is to address #320.  It's still a work in progress. I still need to take a pass to make sure all is well.
As per #320, I removed the Future wrapper for embed's Result param, which cascaded to update, renew and discard methods as well. As you can see in the PR, it removed the need for a lot of Future wrapping.  The only place where complexity was added is [Silhouette#invokeBlock](https://github.com/igorbernstein/play-silhouette/blob/immediate-authenticator-result-params/silhouette/app/com/mohiva/play/silhouette/api/Silhouette.scala#L387-L389) when invoking the handleNotAuthenticated event handler.

Don't wrap results in Futures when passing them to authenticators

---

project/BuildSettings.scala
silhouette-testkit/app/com/mohiva/play/silhouette/test/Fakes.scala
silhouette/app/com/mohiva/play/silhouette/api/Environment.scala
silhouette/app/com/mohiva/play/silhouette/api/Silhouette.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/OAuth1Provider.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/OAuth2Provider.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/OpenIDProvider.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/SocialProvider.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/oauth1/LinkedInProvider.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/oauth1/TwitterProvider.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/oauth1/XingProvider.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/oauth2/ClefProvider.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/oauth2/DropboxProvider.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/oauth2/FacebookProvider.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/oauth2/FoursquareProvider.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/oauth2/GitHubProvider.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/oauth2/GoogleProvider.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/oauth2/InstagramProvider.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/oauth2/LinkedInProvider.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/oauth2/VKProvider.scala
silhouette/test/com/mohiva/play/silhouette/api/SilhouetteSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/OAuth1ProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/OAuth2ProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/OpenIDProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/SocialProviderRegistrySpec.scala

Hi Christian,
I was working on an example Silhouette app based on your seed and ran across an api awkwardness:
Its a bit weird to be lumping all the providers into a single Map...it requires an upcast in SocialAuthController and requires you to handle configuration errors in the CredentialsAuthController  (missing credentials provider).  I was wondering if you would be open to changing the Environment#providers to Environment#requestProviders and updating the seed to inject the CredentialsProvider & SocialProviders in the CredentialsAuthController & SocialAuthController respectfully?

Provider API enhancements 

---

silhouette/app/com/mohiva/play/silhouette/api/Authenticator.scala
silhouette/app/com/mohiva/play/silhouette/api/Silhouette.scala
silhouette/app/com/mohiva/play/silhouette/api/services/AuthenticatorService.scala
silhouette/app/com/mohiva/play/silhouette/impl/authenticators/BearerTokenAuthenticator.scala
silhouette/app/com/mohiva/play/silhouette/impl/authenticators/CookieAuthenticator.scala
silhouette/app/com/mohiva/play/silhouette/impl/authenticators/DummyAuthenticator.scala
silhouette/app/com/mohiva/play/silhouette/impl/authenticators/JWTAuthenticator.scala
silhouette/app/com/mohiva/play/silhouette/impl/authenticators/SessionAuthenticator.scala
silhouette/test/com/mohiva/play/silhouette/api/SilhouetteSpec.scala
silhouette/test/com/mohiva/play/silhouette/api/services/AuthenticatorResultSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/authenticators/DummyAuthenticatorSpec.scala

In every Silhouette action, an authenticator gets automatically [updated](https://github.com/mohiva/play-silhouette/blob/master/silhouette/app/com/mohiva/play/silhouette/api/Silhouette.scala#L275) on every request. This must be done with the result of the action, because every authenticator can update client side data. The problem is now that it isn't possible to manipulate an authenticator manually inside an action, because it gets automatically overridden with the updated authenticator. To work around this issue I've created the methods [discard](https://github.com/mohiva/play-silhouette/blob/master/silhouette/app/com/mohiva/play/silhouette/api/Authenticator.scala#L59) and [renew](https://github.com/mohiva/play-silhouette/blob/master/silhouette/app/com/mohiva/play/silhouette/api/Authenti …

Add method to skip the update of an existing authenticator in a Silhouette action

---

silhouette/app/com/mohiva/play/silhouette/impl/providers/BasicAuthProvider.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/BasicAuthProviderSpec.scala

I ran across this issue when I send requests where the Authorization header was a JWT Bearer such as:
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlNGU1N2Y1NzJhMGU4MjRjMGQxYjZhMzIzMzIxNmUzMmZhYjBiNzMyNDdmNzY3MTBkMmM1OGE2OTEwODA4MmYzZDJlYTVlYTk1YjA0YTA2NjgzM2FjMzU0ZDQwYjk3Y2UxMTE0ZmUyNWNmMjEzYjJkYzllOTAzOWQ0NjQ1OGQ1YyIsImlzcyI6InBsYXktc2lsaG91ZXR0ZSIsImV4cCI6MTQzMDg0NTMxMSwiaWF0IjoxNDMwODAyMTExLCJqdGkiOiJmN2Y1ZThjNmE1MjliYTlkZGYwNjViZjQ5ZGY0MDVjYjQ1ZWEyNmQ3ZTc3NDI5M2Y3NGFhZWVjNTU0ODg1MTVmNTYzMzM5MTM4OGQzY2I3ODA0ZmM4MDIzZjU4ODMzYjk3OGUyMmUxYTZmYzdmNmVkZDJjN2Y5NTVjNDJkM2ZjYTQ2MzVlODZlMzliZjVmZWJjMmI0MzliNzQ2MDU1YzllZjc1ZWFmNzc2MzMxZGU1Yjg4ZmQwMGNhY2U2MjJjZDk0YWMzMzIzNzhkNjNmOTNjZjhkZDUzZGUzODdjYWJiNTgzYTMzYTFjMDIwYjY5MjQ2YTc0MGNhOTY3NDg5ZTRjIn0.mWXfWsFomqMnMBHgZUoHNTO …

BasicAuthProvider should check the method is Basic

---

silhouette-testkit/app/com/mohiva/play/silhouette/test/Fakes.scala
silhouette-testkit/test/com/mohiva/play/silhouette/test/FakesSpec.scala
silhouette/app/com/mohiva/play/silhouette/api/Authorization.scala
silhouette/app/com/mohiva/play/silhouette/api/Environment.scala
silhouette/app/com/mohiva/play/silhouette/api/EventBus.scala
silhouette/app/com/mohiva/play/silhouette/api/SecuredSettings.scala
silhouette/app/com/mohiva/play/silhouette/api/Silhouette.scala
silhouette/app/com/mohiva/play/silhouette/api/util/DefaultEndpointHandler.scala
silhouette/test/com/mohiva/play/silhouette/api/EventBusSpec.scala
silhouette/test/com/mohiva/play/silhouette/api/SecuredSettingsSpec.scala
silhouette/test/com/mohiva/play/silhouette/api/SilhouetteSpec.scala
silhouette/test/com/mohiva/play/silhouette/api/util/DefaultEndpointHandlerSpec.scala

See: https://www.playframework.com/documentation/2.4.x/ScalaI18N

Implement the new Play 2.4 messages API

---

silhouette-testkit/app/com/mohiva/play/silhouette/test/Fakes.scala
silhouette-testkit/test/com/mohiva/play/silhouette/test/FakesSpec.scala

When running tests with `WithApplication` there is always an implicit application in scope. This reduces the need to get the `MessagesApi` from injector and declare it as implicit for the `FakeEnvironment`. Instead the `FakeEnvironment` will fetch it from injector.

Use implicit `Application` instead of the `MessagesApi` to reduce boilerplate code in the tests

---

silhouette/app/com/mohiva/play/silhouette/api/Authorization.scala
silhouette/app/com/mohiva/play/silhouette/api/Silhouette.scala
silhouette/test/com/mohiva/play/silhouette/api/SilhouetteSpec.scala

isAuthorized method use Futures, so now it is possible to avoid Await when you use a DB (like MongoDb) to know if a user is authorized.

Allow to return a Future in the Authorization.isAuthorized method

---

silhouette-testkit/test/com/mohiva/play/silhouette/test/FakesSpec.scala
silhouette/app/com/mohiva/play/silhouette/api/Environment.scala
silhouette/app/com/mohiva/play/silhouette/api/Silhouette.scala
silhouette/test/com/mohiva/play/silhouette/api/SilhouetteSpec.scala

With #335 we have introduced the `MessagesApi` in the `Environment`. But now we have a problem with the `FakeEnvironment`. Typically in a test we need to override the binding for the `Environment` with the `FakeEnvironment`. This must be done before the application is started. But now we have a chicken-and-egg problem, because we need the `FakeEnvironment` to create the application, but the `FakeEnvironment` needs a running application to retrieve the `MessagesApi` binding.
@rfranco Any idea how we can fix this?

Problem with the MessagesApi in the Environment

---

silhouette/app/com/mohiva/play/silhouette/api/util/Base64.scala

Play 2.4 use Java 8 so it can use java.util.Base64

Java 8 Base64

---

silhouette/app/com/mohiva/play/silhouette/api/Authorization.scala
silhouette/app/com/mohiva/play/silhouette/api/Silhouette.scala
silhouette/test/com/mohiva/play/silhouette/api/SilhouetteSpec.scala

The Authorization object can be injected into `SecuredAction` within `SecureAction.apply` method like this:
`SecuredAction(myAuthorization(carID)).async(parse.json) {}`
However, sometimes, the authorization object `myAuthorization(carID)` is unknown until the HTTP body is parsed.  For example, there is a field called `carID` in the POST body, and the constructor for authorization is `myAuthorization(carID)`.  However, `carID` is unknown before the body is parsed, but it seems that the authorization has to be binded and done before body parsing..
Is there a way to set the authorzation outside of SecureAction.apply? 
In other words,  is there a way to start the authorization after body parsing?

Start the Authorization after body parsing?

---

silhouette/app/com/mohiva/play/silhouette/impl/providers/oauth2/FacebookProvider.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/custom/FacebookProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth2/FacebookProviderSpec.scala
silhouette/test/resources/providers/oauth2/clef.access.token.json
silhouette/test/resources/providers/oauth2/facebook.access.token.json

Facebook 2.3 API response with JSON, not url encoded params.

Facebook provider access_token parse error

---

CHANGELOG.md
project/BuildSettings.scala
silhouette-testkit/app/com/mohiva/play/silhouette/test/Fakes.scala
silhouette/app/com/mohiva/play/silhouette/impl/authenticators/CookieAuthenticator.scala
silhouette/app/com/mohiva/play/silhouette/impl/authenticators/JWTAuthenticator.scala
silhouette/app/com/mohiva/play/silhouette/impl/authenticators/SessionAuthenticator.scala
silhouette/test/com/mohiva/play/silhouette/impl/authenticators/CookieAuthenticatorSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/authenticators/JWTAuthenticatorSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/authenticators/SessionAuthenticatorSpec.scala

CookieAuthenticator can now be stateless without a backing store and some other small authenticator enhancements

Stateless and non-stateless CookieAuthenticator

---

silhouette/app/com/mohiva/play/silhouette/api/Authenticator.scala
silhouette/app/com/mohiva/play/silhouette/api/services/AuthenticatorService.scala
silhouette/app/com/mohiva/play/silhouette/impl/authenticators/BearerTokenAuthenticator.scala
silhouette/app/com/mohiva/play/silhouette/impl/authenticators/CookieAuthenticator.scala
silhouette/app/com/mohiva/play/silhouette/impl/authenticators/DummyAuthenticator.scala
silhouette/app/com/mohiva/play/silhouette/impl/authenticators/JWTAuthenticator.scala
silhouette/app/com/mohiva/play/silhouette/impl/authenticators/SessionAuthenticator.scala

Move type for the `Settings` to `Authenticator` to allow the usage of the `withSettings` method on a `AuthenticatorService[Authenticator]` instance.

Move type for the settings to authenticator

---

silhouette/app/com/mohiva/play/silhouette/impl/providers/oauth1/TwitterProvider.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth1/TwitterProviderSpec.scala
silhouette/test/resources/providers/oauth1/twitter.with.email.json

Earlier in 2015 twitter added the ability for applications to retrieve user emails. Applications have to be specifically whitelisted in order to do this, and an additional token has to be sent along with the request to verify_credentials in order for the email to be returned.

Twitter Provider: add email support

---

silhouette/app/com/mohiva/play/silhouette/impl/authenticators/BearerTokenAuthenticator.scala
silhouette/app/com/mohiva/play/silhouette/impl/authenticators/CookieAuthenticator.scala
silhouette/app/com/mohiva/play/silhouette/impl/authenticators/JWTAuthenticator.scala
silhouette/app/com/mohiva/play/silhouette/impl/authenticators/SessionAuthenticator.scala

If we use an other default value as `None` for `Option` based setting keys, then we do not have the possibility to set `None` as value in the Play configuration. Because if we omit the config property or if we use `null` as value, then the Typesafe config implementation will use the default value for this property.

Use None as default value for Option based settings values

---

silhouette/app/com/mohiva/play/silhouette/api/Authenticator.scala
silhouette/app/com/mohiva/play/silhouette/api/services/AuthenticatorService.scala
silhouette/app/com/mohiva/play/silhouette/impl/authenticators/BearerTokenAuthenticator.scala
silhouette/app/com/mohiva/play/silhouette/impl/authenticators/CookieAuthenticator.scala
silhouette/app/com/mohiva/play/silhouette/impl/authenticators/DummyAuthenticator.scala
silhouette/app/com/mohiva/play/silhouette/impl/authenticators/JWTAuthenticator.scala
silhouette/app/com/mohiva/play/silhouette/impl/authenticators/SessionAuthenticator.scala
silhouette/test/com/mohiva/play/silhouette/api/AuthenticatorSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/authenticators/BearerTokenAuthenticatorSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/authenticators/CookieAuthenticatorSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/authenticators/DummyAuthenticatorSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/authenticators/JWTAuthenticatorSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/authenticators/SessionAuthenticatorSpec.scala

* Add explicit "Remember Me" functionality to the CookieAuthenticator
* Remove the `withSettings` method from the `AuthenticatorService` because it doesn't work as expected
* Rename the `DateTime` based variable names to `dateTime` instead of `date` to better signalize the associated type of the variable
* Encapsulate functionality for expiring authenticators into the `ExpirableAuthenticator` trait

Big authenticator refactoring

---

.travis.yml
project/BuildSettings.scala
scripts/sbt-runner
silhouette/app/com/mohiva/play/silhouette/impl/providers/BasicAuthProvider.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/BasicAuthProviderSpec.scala

Currently the `BasicAuthProvider` throws an exception if the identity was not found or if the password does not match. For request providers there is no change for the developer to react to these errors. Furthermore it breaks the request provider chain.

BasicAuthProvider should not throw exception for user errors

---

project/BuildSettings.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/CredentialsProvider.scala

By default the credentials provider creates the login info with the identifier entered in the form. For some cases this may not be enough. It could also be possible that a login form allows a user to log in with either a username or an email address. In this case, the `loginInfo` method provided with this pull request, should be overridden to provide a unique binding, like the user ID, for the entered form values.
See: http://silhouette.mohiva.com/v3.0/discuss/56002d146932a00d00ba7bd9

Allow to override the creation of the LoginInfo for the CredentialsProvider

---

CHANGELOG.md
silhouette/app/com/mohiva/play/silhouette/api/RequestHandler.scala
silhouette/app/com/mohiva/play/silhouette/api/Silhouette.scala
silhouette/app/com/mohiva/play/silhouette/api/actions/SecuredAction.scala
silhouette/app/com/mohiva/play/silhouette/api/actions/UnsecuredAction.scala
silhouette/app/com/mohiva/play/silhouette/api/actions/UserAwareAction.scala
silhouette/conf/reference.conf
silhouette/test/com/mohiva/play/silhouette/api/actions/SecuredActionSpec.scala
silhouette/test/com/mohiva/play/silhouette/api/actions/UnsecuredActionSpec.scala

It should be possible for an application to restrict access to an action for already authenticated users. If a user is already signed-in then it shouldn't possible for the user to access the sign-in or sign-up page. Instead he should be redirected to another page.

Add a new action type that restricts access for authenticated users

---

silhouette/app/com/mohiva/play/silhouette/api/services/AuthenticatorService.scala
silhouette/app/com/mohiva/play/silhouette/api/util/RequestExtractor.scala
silhouette/app/com/mohiva/play/silhouette/impl/authenticators/BearerTokenAuthenticator.scala
silhouette/app/com/mohiva/play/silhouette/impl/authenticators/CookieAuthenticator.scala
silhouette/app/com/mohiva/play/silhouette/impl/authenticators/DummyAuthenticator.scala
silhouette/app/com/mohiva/play/silhouette/impl/authenticators/JWTAuthenticator.scala
silhouette/app/com/mohiva/play/silhouette/impl/authenticators/SessionAuthenticator.scala
silhouette/test/com/mohiva/play/silhouette/api/util/Base64Spec.scala
silhouette/test/com/mohiva/play/silhouette/api/util/ClockSpec.scala
silhouette/test/com/mohiva/play/silhouette/api/util/PlayHTTPLayerSpec.scala
silhouette/test/com/mohiva/play/silhouette/api/util/RequestExtractorSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/authenticators/BearerTokenAuthenticatorSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/authenticators/CookieAuthenticatorSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/authenticators/JWTAuthenticatorSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/authenticators/SessionAuthenticatorSpec.scala

Sometimes it may be necessary to send the authenticator specific values in other parts of the request. If we use a request extractor in the `retrieve` method of the authenticator service, then it may be possible to send a bearer token as example in the query string instead of the header.
See: http://silhouette.mohiva.com/v3.0/discuss/55950f4935f567170094304c

Use request extractors to find authenticator values in other parts of the request

---

silhouette/app/com/mohiva/play/silhouette/impl/providers/OAuth1Provider.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/OpenIDProvider.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/oauth1/LinkedInProvider.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/oauth1/TwitterProvider.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/oauth1/XingProvider.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/oauth1/services/PlayOAuth1Service.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/openid/SteamProvider.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/openid/YahooProvider.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/openid/services/PlayOpenIDService.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/OAuth1ProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth1/LinkedInProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth1/TwitterProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth1/XingProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth1/services/PlayOAuth1ServiceSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/openid/SteamProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/openid/YahooProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/openid/service/PlayOpenIDServiceSpec.scala

This PR fixes #432. Some notes: 
There are three flavours of SocialProvider: OAuth1, OpenID and OAuth2. OAuth1 and OpenID related services only hold references into its respective first level settings objects (OAuth1Settings and OpenIDSettings). That makes `withSettings` API really appropriate. However OAuth2 related services (e.g CookieStateProvider) have different settings objects: CookieStateSettings vs OAuth2Settings. That means that this API could be misleading for OAuth2 scenarios, it seems that we're updating every settings value related with that OAuth2 provider but actually we're only updating OAuth2Settings instances. That's out of the scope for this fix, as it would probably involve a new API or updating the existing one, but I'd like to note it.
About OAuth1 and OpenID, one of …

Fix overriding settings method for Providers.

---

silhouette/app/com/mohiva/play/silhouette/impl/providers/OAuth1Provider.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/OAuth2Provider.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/OpenIDProvider.scala

How to override `ClientID` in `object OAuth2Provider`? See the code [here](https://github.com/mohiva/play-silhouette/blob/1efb38af36f1f590af1ca988f0e7d02793255c1a/silhouette/app/com/mohiva/play/silhouette/impl/providers/OAuth2Provider.scala#L185). Some OAuth2 provider like wechat don't use `client_id` but `appid`.

Allow to override authentication provider constants

---

scripts/ci-build
silhouette-persistence-memory/src/test/scala/com/mohiva/play/silhouette/persistence/memory/daos/OAuth1InfoDAOSpec.scala
silhouette-persistence-memory/src/test/scala/com/mohiva/play/silhouette/persistence/memory/daos/OAuth2InfoDAOSpec.scala
silhouette-persistence-memory/src/test/scala/com/mohiva/play/silhouette/persistence/memory/daos/OpenIDInfoDAOSpec.scala
silhouette-persistence-memory/src/test/scala/com/mohiva/play/silhouette/persistence/memory/daos/PasswordInfoDAOSpec.scala
silhouette-persistence-memory/src/test/scala/com/mohiva/play/silhouette/test/WaitPatience.scala
silhouette-persistence/src/test/scala/com/mohiva/play/silhouette/persistence/daos/InMemoryAuthInfoDAOSpec.scala
silhouette-persistence/src/test/scala/com/mohiva/play/silhouette/persistence/repositories/CacheAuthenticatorRepositorySpec.scala
silhouette-persistence/src/test/scala/com/mohiva/play/silhouette/persistence/repositories/DelegableAuthInfoRepositorySpec.scala
silhouette-persistence/src/test/scala/com/mohiva/play/silhouette/test/WaitPatience.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth1/LinkedInProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth1/TwitterProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth1/XingProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth2/ClefProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth2/DropboxProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth2/FacebookProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth2/FoursquareProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth2/GitHubProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth2/GoogleProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth2/InstagramProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth2/LinkedInProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth2/VKProviderSpec.scala

Since the introduction of API URL override in ad7bcdc5 the build was
inevitably broken because of a wrong Mockito validate statement. 
Travis did not detect the breakage because of the missing "-e" option
on the bash execution, thus the final "echo" was shallowing the exit
code of the test.
This change fixes the build ci script *AND* the Mockito validation
statement.

Fix broken tests introduced in ad7bcdc5

---

silhouette-password-bcrypt/src/main/scala/com/mohiva/play/silhouette/password/BCryptPasswordHasher.scala
silhouette-password-bcrypt/src/test/scala/com/mohiva/play/silhouette/password/BCryptPasswordHasherSpec.scala
silhouette-persistence/src/test/scala/com/mohiva/play/silhouette/test/WaitPatience.scala
silhouette/app/com/mohiva/play/silhouette/api/util/PasswordHasher.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/BasicAuthProvider.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/CredentialsProvider.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/PasswordProvider.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/BasicAuthProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/CredentialsProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/PasswordProviderSpec.scala

WIP
In contrast to the current implementation it now defines the clear responsibility for every component. Currently this is defined squishy in the interface and therefore can lead to bugs like #454 or #459.
What are the changes for the user:
It's now unambiguous when a password hasher or a password is deprecated and when it should be updated with a newer algorithm. This is now defined through the `PasswordHasherRegistry`. It accepts two parameters. The current preferred algorithm and the list of deprecated hashers which are needed to macht the old hashes which are stored in the database.
So to instantiate the `CredentialsProvider` as example, a user must now write:
```scala
new CredentialsProvider(..., new PasswordHasherRegistry(new BCryptPassordHasher(10)))
```
instead of
```scala
new …
```

Define meaningful interface for password re-hashing

---

silhouette/app/com/mohiva/play/silhouette/api/ErrorHandler.scala
silhouette/test/com/mohiva/play/silhouette/api/ErrorHandlerSpec.scala

Play: 2.5.1
Silhouette: 4.0.0-BETA4
```
def postAny() = silhouette.SecuredAction.async { request =>
Future.successful(Ok(""))
}
```
If that action is requested without authentication headers, play 2.5 prints
`[warn] - play.core.server.netty.NettyModelConversion - Content-Type set both in header (text/html; charset=utf-8) and attached to entity (text/html; charset=utf-8), ignoring content type from entity. To remove this warning, use Result.as(...) to set the content type, rather than setting the header manually.`
Looks like `DefaultErrorHandler.produceResponse` should not use `.withHeaders(HeaderNames.CONTENT_TYPE -> ContentTypes.JSON)`

Accessing SecuredAction without authentication warns about duplicate Content-Type

---

silhouette-persistence-memory/src/main/resources/reference.conf

Fixes #466 https://github.com/mohiva/play-silhouette-angular-seed/issues/42
Removes the `reference.conf` from module and therefore remove the default binding for the `PersistenceModule`.
Defining the default binding when the module is included isn't a good idea, because it confuses people and it makes it hard to define a custom `AuthInfoRepository` because then the module must first be disabled.

Remove default binding for persistence memory module

---

silhouette-cas/src/main/scala/com/mohiva/play/silhouette/impl/providers/cas/CasProvider.scala
silhouette-cas/src/test/scala/com/mohiva/play/silhouette/impl/providers/cas/CasProviderSpec.scala

Fixes an issue in the CasProvider where an incorrect LoginInfo object was being constructed.
The unit tests pass as they are contrived. However the previous code falls over at runtime.

Fixing issue with CAS username

---

project/BuildSettings.scala
silhouette/app/com/mohiva/play/silhouette/api/exceptions/CryptoException.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/oauth1/secrets/CookieSecret.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/oauth2/state/CookieState.scala
silhouette/app/com/mohiva/play/silhouette/impl/util/CookieSigner.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth1/secrets/CookieSecretSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth2/state/CookieStateSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/util/CookieSignerSpec.scala

Cookies are currently not signed, which allows an attacker arbitrarily modifying the cookie value.

Sign cookies with HMAC

---

silhouette/app/com/mohiva/play/silhouette/api/ErrorHandler.scala

This PR allows users to override the error format methods when extending `DefaultSecuredErrorHandler`
This was discussed in the [Gitter](https://gitter.im/mohiva/play-silhouette) channel.

Allow error format methods to be overridden

---

silhouette-crypto-jca/src/main/scala/com/mohiva/play/silhouette/crypto/JcaSigner.scala
silhouette-crypto-jca/src/test/scala/com/mohiva/play/silhouette/crypto/JcaSignerSpec.scala
silhouette-testkit/app/com/mohiva/play/silhouette/test/Fakes.scala
silhouette/app/com/mohiva/play/silhouette/api/crypto/Signer.scala
silhouette/app/com/mohiva/play/silhouette/impl/authenticators/CookieAuthenticator.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/SocialStateProvider.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/oauth1/secrets/CookieSecret.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/state/CsrfStateItemHandler.scala
silhouette/test/com/mohiva/play/silhouette/impl/authenticators/CookieAuthenticatorSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/DefaultSocialStateHandlerSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth1/secrets/CookieSecretSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/state/CsrfStateItemHandlerSpec.scala

Until now we have only signed cookies, but now we sign also the social state sent to the provider. So we renamed the cookie signer to signer to avoid confusion.

Rename cookie signer to signer

---

silhouette/app/com/mohiva/play/silhouette/api/services/AuthenticatorService.scala

In play-silhouette with play 2.6.0-RC2, authenticator cookie is not getting returned after successful sign in. This fix removes the default values for copy method in AuthenticatorResult which was leading to cleaning up of authenticator cookie.
Providing default for copy leads to emptying out of parameters in scala. Here is a simple program to understand this behavior in scala:
```scala
case class Foo(p1: String, p2: String) {}
class Bar(p1: String, p2: String) extends Foo(p1, p2) {
override def copy(arg1: String = "", arg2: String = ""): Foo = { Foo(arg1, arg2) }
}
val x = new Bar("hello", "world")
val y: Foo = x
val z = y.copy(p2 = "blah")
```
Now z is Foo(,blah) instead of Foo("hello", "blah")

Fix for CookieAuthenticator not working with Play 2.6.0-RC2

---

project/BuildSettings.scala
project/Dependencies.scala
silhouette/app/com/mohiva/play/silhouette/impl/authenticators/CookieAuthenticator.scala
silhouette/app/com/mohiva/play/silhouette/impl/authenticators/SessionAuthenticator.scala
silhouette/test/com/mohiva/play/silhouette/impl/authenticators/BearerTokenAuthenticatorSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/authenticators/CookieAuthenticatorSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/authenticators/JWTAuthenticatorSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/authenticators/SessionAuthenticatorSpec.scala

Some authenticators override the request attributes and remove all other request parts.

Authenticators should keep other request parts in test mode

---

silhouette/app/com/mohiva/play/silhouette/impl/providers/SocialStateProvider.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/DefaultSocialStateHandlerSpec.scala

The problem is that the `getOrElse` method returns the result passed to the `publish` method and not the accumulated result. So if a non publishable state items comes after a publishable state item, then it overrides the result with original result and therefore throws away all changes made by the publishable item.
https://gitter.im/mohiva/play-silhouette?at=59e49918b20c6424290ae0e2

State handler uses wrong result if a user state item is used

---

silhouette/app/com/mohiva/play/silhouette/impl/providers/state/CsrfStateItemHandler.scala

When using `DefaultSocialStateHandler` with `CsrfStateItemHandler` it might happen that `CsrfStateItemHandler.canHandle` would return `false` and user would not know exactly whats wrong because `clientState` `Failure` was ignored. 
I've added `warn` log before returning `false` so user can have an idea during development process.

Log warning message when validating csrf token item handler state

---

silhouette/app/com/mohiva/play/silhouette/impl/providers/oauth2/VKProvider.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth2/VKProviderSpec.scala
silhouette/test/resources/providers/oauth2/vk.success.deprecated.json
silhouette/test/resources/providers/oauth2/vk.success.json
silhouette/test/resources/providers/oauth2/vk.success.without.photo.json

Fixes VKProvider's API calls resulting in an error:
```
{
"error_code":8,
"error_msg":"Invalid request: v (version) is required"
}
```
Update VKProvider's API calls according to VK API changes.
VK has updated their API so now calls to `https://api.vk.com/method/getProfiles` without v-for-version parameter result in an error. See References for details.
https://vk.com/dev/version_update

Fix VKProvider's deprecated API calls

---

silhouette/app/com/mohiva/play/silhouette/impl/providers/oauth2/GoogleProvider.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth2/GoogleProviderSpec.scala
silhouette/test/resources/providers/oauth2/google.img.default.json
silhouette/test/resources/providers/oauth2/google.img.non-default.json

-> N/A
n/a, it's an improvement.
Adds functionality to suppress the default Google profile image. 
Silhouette provides it's own placeholder profile image when a user does not have an avatar image set.
The Google+ API however will always return a profile image URL, which is a standard image and looks different from the OOTB Silhouette placeholder image. This change inspects a flag in the response (isDefault) and ignores the returned image URL if true.
Yupp, as discussed on Gitter.

GoogleProvider: Suppress Google's default profile picture

---

silhouette/app/com/mohiva/play/silhouette/impl/authenticators/CookieAuthenticator.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/oauth1/secrets/CookieSecret.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/state/CsrfStateItemHandler.scala
silhouette/test/com/mohiva/play/silhouette/impl/authenticators/CookieAuthenticatorSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/state/CsrfStateItemHandlerSpec.scala

Makes it possible to set the SameSite option on cookies.
~~I chose to use a String representation, since using the Cookie.SameSite type, would break current solutions using Ficus. Alternatively we could create our own Enumeration and convert that to the Play Cookie.SameSite type.~~ EDIT: We're now using the Cookie.SameSite type.
I chose the default to be `Lax`, since from looking at other settings, we want to recommend a sane default, where as `Strict`, might be too harsh, and `None` would simply do nothing.

Added support for setting the SameSite option on cookies.

---

silhouette/app/com/mohiva/play/silhouette/impl/providers/oauth2/GoogleProvider.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth2/GoogleProviderSpec.scala
silhouette/test/resources/providers/oauth2/google.error.api.missing.json
silhouette/test/resources/providers/oauth2/google.img.default.json
silhouette/test/resources/providers/oauth2/google.img.non-default.json
silhouette/test/resources/providers/oauth2/google.success.json
silhouette/test/resources/providers/oauth2/google.without.email.json

Changed the API endpoint and response parsing to new People API.
Updated the test json files. Added a new test if a project is not enabled for the People API.
Google sunsetted the Google+ API and need to switch to the People API.
Current API is going to be retired in March 2019. So it's time to update. 
https://github.com/mohiva/play-silhouette/issues/548

#548: Switch GoogleProvider to People API

---

.gitignore
.travis.yml
CHANGELOG.md
project/BuildSettings.scala
project/Dependencies.scala
project/plugins.sbt
scripts/sbt
scripts/sbt-runner
silhouette-cas/src/main/scala/com/mohiva/play/silhouette/impl/providers/CasProvider.scala
silhouette-cas/src/test/scala/com/mohiva/play/silhouette/impl/providers/CasProviderSpec.scala
silhouette-persistence/src/test/scala/com/mohiva/play/silhouette/persistence/repositories/DelegableAuthInfoRepositorySpec.scala
silhouette/app-2.13+/com/mohiva/play/silhouette/ScalaCompat.scala
silhouette/app-2.13-/com/mohiva/play/silhouette/ScalaCompat.scala
silhouette/app/com/mohiva/play/silhouette/impl/authenticators/JWTAuthenticator.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/OAuth2Provider.scala
silhouette/build.sbt
silhouette/test/com/mohiva/play/silhouette/impl/providers/OAuth2ProviderSpec.scala

- add Scala 2.13.0 support and adjust code to get
2.11, 2.12 and 2.13 working together.
- bump dependencies / plugins necessary to get 2.13.0 support.
- add 2.13.0 to travis ci and ensure that sbt runs with correct
Scala version.
- update sbt-runner to [paulp/sbt-extras@0ee2dae](https://github.com/paulp/sbt-extras/commit/0ee2dae2eba72efb4a464a5ad255e348696ecda7)
- add notes to change log.

all: Scala 2.13.0 support

---

silhouette-totp/src/main/scala/com/mohiva/play/silhouette/impl/providers/GoogleTotpProvider.scala

I want to create a class that inherits GoogleTotpProider and inject id dynamically.
```
class CustomTotpProvider @Inject()(
override val id: String,
passwordHasherRegistry: PasswordHasherRegistry
)(implicit ec: ExecutionContext)
extends GoogleTotpProvider(passwordHasherRegistry) {
...
}
```
However, the authenticate method always returns the same ID ("googleTotp").
```
def authenticate(sharedKey: String, verificationCode: String): Future[Option[LoginInfo]] = {
Future(
if (isVerificationCodeValid(sharedKey, verificationCode)) {
Some(LoginInfo(ID, sharedKey))
^^
...
```

Fix that GoogleTotpProvider ID is can not override.

---

silhouette/app/com/mohiva/play/silhouette/impl/providers/oauth2/LinkedInProvider.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth2/LinkedInProviderSpec.scala
silhouette/test/resources/providers/oauth2/linkedin.email.json
silhouette/test/resources/providers/oauth2/linkedin.error.json
silhouette/test/resources/providers/oauth2/linkedin.photo.json
silhouette/test/resources/providers/oauth2/linkedin.success.json

This fix updates the API url to the v2 resource and the parsing of the json response that comes from it.
This PR allows you to user the LinkedIn provider and get the First and Last name of the logged user. Unfortunatelly the email and picture don't come by default anymore and for that reason were left out.
It has been a while since LinkedIn has discontinued its v1 people resource. As a result, the LinkedInProvider was failing to parse the profile of the logged user.

Fixed Profile URL as v1 resource is no longer available

---

.travis.yml
project/BuildSettings.scala
project/Dependencies.scala
project/build.properties
project/plugins.sbt

As a rule of thumb, a scalac plugin always should be published using the full
scala version in its name, since scalac's internal APIs can change without notice.
This change introduces the sbt-travisci plugin which makes it easier to
maintain a full set of versions, cross compiled and run through the CI.
Fixes build issue with Scala 2.13.1 (See #https://github.com/scala/bug/issues/11742)

Fix build error regarding binary incompatibility between scala 2.13.0 and 2.13.1 compiler

---

silhouette/app/com/mohiva/play/silhouette/api/actions/SecuredAction.scala
silhouette/app/com/mohiva/play/silhouette/api/actions/UserAwareAction.scala

This PR changes `SecuredRequest` from a case class to a trait, and adds a `SecuredRequestHeader` trait as well.
This makes it easier to change the implementation of a secured request because a wrapped request may want to implement secured request behavior, i.e. the identity and authenticator, but cannot because there is not a trait for it.
Because there is a factory method which uses the default impl behind the scenes, this should have no impact on user facing code (although I have not tried binary compatibility, etc.)
This is the approach used for extending Play requests internally, i.e. in https://github.com/playframework/playframework/blob/2.6.x/core/play/src/main/scala/play/api/mvc/MessagesRequest.scala
Note that the request body should be covariant per …

Make SecuredRequest and UserAwareRequest traits

---

silhouette/app/com/mohiva/play/silhouette/impl/providers/oauth2/GitHubProvider.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth2/GitHubProviderSpec.scala

Updates `GitHubProvider` to send the OAuth2 token via an authorization header instead of a query param. This is needed as GitHub have deprecated the query param mechanism and are notifying API users periodically about this.
**Note:** this might be a breaking change for any users that have overridden the GitHub URL.
Based the changes on the Dropbox provider which also sends via a header.
* GitHub Developer [blog post](https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters) discussing the deprecation.

Update GitHubProvider to send token via header

---

silhouette/app/com/mohiva/play/silhouette/impl/providers/oauth2/Auth0Provider.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth2/Auth0ProviderSpec.scala

- Auth0's userinfo API returns sub as user's ID; doesn't have user_id
- It returns name as user's full name
- Also fixed comment of auth0.scope to get user's profile

Fixed Auth0ProfileParser to get user id and name
