app/com/mohiva/play/silhouette/impl/providers/OAuth2Provider.scala
app/com/mohiva/play/silhouette/impl/providers/oauth2/state/CookieState.scala
app/com/mohiva/play/silhouette/impl/providers/oauth2/state/DummyState.scala
docs/how-it-works/providers.rst
test/com/mohiva/play/silhouette/impl/providers/OAuth2ProviderSpec.scala
test/com/mohiva/play/silhouette/impl/providers/oauth2/state/CookieStateSpec.scala
test/com/mohiva/play/silhouette/impl/providers/oauth2/state/DummyStateSpec.scala

@see https://github.com/mohiva/play-silhouette/pull/233#issuecomment-68920618

Add dummy state and add implicit request to the build method

---

CHANGELOG.md
docs/configuration.rst
docs/how-it-works/providers.rst
silhouette/app/com/mohiva/play/silhouette/impl/providers/openid/SteamProvider.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/openid/SteamProviderSpec.scala

Consider adding support for authentication with Steam OpenID.
https://steamcommunity.com/dev
http://stackoverflow.com/questions/22041522/steam-openid-and-play-framework

Steam OpenID integration

---

docs/how-it-works/authenticator.rst
docs/how-it-works/caching.rst
docs/how-it-works/environment.rst
docs/how-it-works/providers.rst

Done by the following command, hoping to fix every broken link:
`find . -name '*.rst' | xargs sed -i 's_blob/master/app_blob/master/silhouette/app_'`

Fix more hyperlinks to source files

---

CHANGELOG.md
docs/configuration.rst
docs/how-it-works/providers.rst
silhouette/app/com/mohiva/play/silhouette/impl/providers/oauth2/ClefProvider.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth2/ClefProviderSpec.scala
silhouette/test/resources/providers/oauth2/clef.access.token.json
silhouette/test/resources/providers/oauth2/clef.error.json
silhouette/test/resources/providers/oauth2/clef.success.json

Consider adding support for authentication with Clef.
https://getclef.com/

Clef integration

---

silhouette/test/com/mohiva/play/silhouette/impl/authenticators/CookieAuthenticatorSpec.scala

Recent [Travis build failure](https://travis-ci.org/mohiva/play-silhouette/jobs/48472754#L1838-L1842) looks weird. The failing test is in [CookieAuthenticatorSpec](https://github.com/mohiva/play-silhouette/blob/master/silhouette/test/com/mohiva/play/silhouette/impl/authenticators/CookieAuthenticatorSpec.scala#L214-L223) which tests cookie embedding into a `Future[Result]`.
Both cookies before and after embedding are the same except `maxAge`, which is hardcoded at [CookieAuthenticator::cookie](https://github.com/mohiva/play-silhouette/blob/master/silhouette/test/com/mohiva/play/silhouette/impl/authenticators/CookieAuthenticatorSpec.scala#L433).

Weird test failure

---

silhouette/app/com/mohiva/play/silhouette/impl/util/DefaultFingerprintGenerator.scala
silhouette/test/com/mohiva/play/silhouette/impl/util/DefaultFingerprintGeneratorSpec.scala

I've tried https://github.com/mohiva/play-silhouette-seed, for example. One, maybe two days ago it worked, now it doesn't. On my machine(Ubuntu 14.04) it works correctly only on Firefox, and not on Chrome, Opera and Vivaldi. The error is - after signing up I cannot sign in with email and password. authenticate action works correctly, but request.identity is None.

Silhouette stopped working

---

docs/how-it-works/identity.rst
docs/how-it-works/testing.rst
silhouette-testkit/app/com/mohiva/play/silhouette/test/Fakes.scala
silhouette-testkit/test/com/mohiva/play/silhouette/test/FakesSpec.scala
silhouette/app/com/mohiva/play/silhouette/api/Identity.scala
silhouette/app/com/mohiva/play/silhouette/api/LoginInfo.scala

@see https://groups.google.com/forum/#!topic/play-silhouette/XiItX-P3ZP0

Remove LoginInfo from Identity trait

---

CHANGELOG.md
docs/configuration.rst
docs/how-it-works/providers.rst
silhouette/app/com/mohiva/play/silhouette/impl/providers/OAuth1Provider.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/OAuth2Provider.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/oauth1/LinkedInProvider.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/oauth1/TwitterProvider.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/oauth1/XingProvider.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/oauth1/exceptions/TokenSecretException.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/oauth1/secrets/CookieSecret.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/oauth2/exceptions/StateException.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/oauth2/state/CookieState.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/OAuth1ProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/OAuth2ProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth1/LinkedInProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth1/TwitterProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth1/XingProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth1/secrets/CookieSecretSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth2/state/CookieStateSpec.scala

Hello, 
first of all, nice lib. Anyways, I am currently involved in a project where we replaced a custom made social-access implementation with play-silhouette. Every social platform supported works, except Xing. 
There seems to be an issue with Silhouette, since our former implementation for Xing works. (Play 2.3.7). 
Could anyone verify that Xing works for them?
Thx.

[Silhouette][xing] Error retrieving access token]]

---

docs/configuration.rst
silhouette/app/com/mohiva/play/silhouette/impl/providers/OAuth2Provider.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/oauth2/VKProvider.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth2/VKProviderSpec.scala
silhouette/test/resources/providers/oauth2/vk.access.token.json

@see https://groups.google.com/forum/#!topic/play-silhouette/XvlK_8-ltJg

Obtain email address from VK provider

---

silhouette/app/com/mohiva/play/silhouette/impl/authenticators/JWTAuthenticator.scala
silhouette/test/com/mohiva/play/silhouette/impl/authenticators/JWTAuthenticatorSpec.scala

@see #290 
This pull request adds the possibility to add arbitrary Json data to the `JWTAuthenticator` after creation.

Fixes #290

---

silhouette/app/com/mohiva/play/silhouette/impl/services/GravatarService.scala
silhouette/test/com/mohiva/play/silhouette/impl/services/GravatarServiceSpec.scala

@see https://github.com/jaliss/securesocial/pull/533

Hash leading zeros get trimmed

---

silhouette/app/com/mohiva/play/silhouette/api/LoginInfo.scala

Add tupled method to LoginInfo companion object.

#363 LoginInfo explicit companion object.

---

silhouette/app/com/mohiva/play/silhouette/api/Authorization.scala
silhouette/app/com/mohiva/play/silhouette/api/Silhouette.scala
silhouette/test/com/mohiva/play/silhouette/api/SilhouetteSpec.scala

With this enhancement it's possible to reject requests based on the authenticator.
See discussion: https://groups.google.com/forum/#!topic/play-silhouette/2fCNfnkCPxI

Add authenticator to Authorization.isAuthorized method

---

CHANGELOG.md
silhouette/app/com/mohiva/play/silhouette/api/util/JsonFormats.scala
silhouette/app/com/mohiva/play/silhouette/impl/authenticators/BearerTokenAuthenticator.scala
silhouette/app/com/mohiva/play/silhouette/impl/authenticators/CookieAuthenticator.scala
silhouette/app/com/mohiva/play/silhouette/impl/authenticators/JWTAuthenticator.scala
silhouette/app/com/mohiva/play/silhouette/impl/authenticators/SessionAuthenticator.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/OpenIDProvider.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/oauth1/secrets/CookieSecret.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/oauth2/state/CookieState.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/openid/services/PlayOpenIDService.scala
silhouette/test/com/mohiva/play/silhouette/api/util/JsonFormatsSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/openid/YahooProviderSpec.scala

- Use FiniteDuration instead of Duration for duration based values
- Use Map[String, String] instead of Seq[(String, String)] for the OpenIDSettings

Polish settings types

---

silhouette/app/com/mohiva/play/silhouette/impl/authenticators/CookieAuthenticator.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/oauth1/secrets/CookieSecret.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/oauth2/state/CookieState.scala

Better alternative for https://github.com/mohiva/play-silhouette/pull/382

Remove global state for configuration values

---

project/BuildSettings.scala
project/plugins.sbt
silhouette/app/com/mohiva/play/silhouette/impl/providers/BasicAuthProvider.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/BasicAuthProviderSpec.scala

BasicAuthProvider fails if a colon is contained in the password

---

project/BuildSettings.scala
silhouette/app/com/mohiva/play/silhouette/api/Silhouette.scala

The bug described in #406 affects also the master branch

Fixes #406

---

silhouette/app/com/mohiva/play/silhouette/api/util/Crypt.scala
silhouette/app/com/mohiva/play/silhouette/impl/util/DefaultFingerprintGenerator.scala
silhouette/test/com/mohiva/play/silhouette/api/util/CryptSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/util/DefaultFingerprintGeneratorSpec.scala

See https://github.com/akka/akka/issues/16330

Do not use akka.util.Crypt.sha1

---

CHANGELOG.md
silhouette/app/com/mohiva/play/silhouette/impl/providers/SocialProvider.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/oauth1/LinkedInProvider.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/oauth1/TwitterProvider.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/oauth1/XingProvider.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/oauth2/ClefProvider.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/oauth2/DropboxProvider.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/oauth2/FacebookProvider.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/oauth2/FoursquareProvider.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/oauth2/GitHubProvider.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/oauth2/GoogleProvider.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/oauth2/InstagramProvider.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/oauth2/LinkedInProvider.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/oauth2/VKProvider.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/openid/SteamProvider.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/openid/YahooProvider.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/custom/FacebookProviderSpec.scala

@see http://stackoverflow.com/a/33031783/2153190

Pass the auth info for the profile parsers

---

.gitignore
.travis.yml
CHANGELOG.md
project/Dependencies.scala
project/plugins.sbt
silhouette/app/com/mohiva/play/silhouette/impl/authenticators/BearerTokenAuthenticator.scala
silhouette/app/com/mohiva/play/silhouette/impl/authenticators/CookieAuthenticator.scala
silhouette/app/com/mohiva/play/silhouette/impl/authenticators/JWTAuthenticator.scala
silhouette/app/com/mohiva/play/silhouette/impl/authenticators/SessionAuthenticator.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/OAuth2Provider.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/oauth2/state/CookieState.scala
silhouette/app/com/mohiva/play/silhouette/package.scala
silhouette/test/com/mohiva/play/silhouette/api/EventBusSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/authenticators/DummyAuthenticatorSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/SocialProviderRegistrySpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/util/PlayCacheLayerSpec.scala

Play 2.5 drops Scala 2.10 support so we do it as well

Drop Scala 2.10 support

---

silhouette/app/com/mohiva/play/silhouette/impl/authenticators/JWTAuthenticator.scala
silhouette/test/com/mohiva/play/silhouette/impl/authenticators/JWTAuthenticatorSpec.scala

this should fix issue#435.  is there anything else that should be copied?  idleTimeout, maybe?

issue#435 * copy customClaims when renewing JWTToken

---

silhouette/app/com/mohiva/play/silhouette/impl/providers/oauth2/Auth0Provider.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth2/Auth0ProviderSpec.scala
silhouette/test/resources/providers/custom/auth0.error.json
silhouette/test/resources/providers/custom/auth0.profile.json
silhouette/test/resources/providers/custom/auth0.success.json

Introduce the support of Auth0.com, a popular authentication service
which exposes a OAuth 2.0 provider interface.

Support for Auth0 authentication provider

---

silhouette-password-bcrypt/src/main/scala/com/mohiva/play/silhouette/password/BCryptPasswordHasher.scala
silhouette-password-bcrypt/src/test/scala/com/mohiva/play/silhouette/password/BCryptPasswordHasherSpec.scala
silhouette/app/com/mohiva/play/silhouette/api/util/PasswordHasher.scala

Fixes https://github.com/mohiva/play-silhouette/pull/454

Password hashers should not only be equal based on types

---

project/BuildSettings.scala
project/Dependencies.scala
project/plugins.sbt
silhouette-persistence-memory/src/main/resources/reference.conf
silhouette-persistence-memory/src/main/scala/com/mohiva/play/silhouette/persistence/memory/modules/PersistenceModule.scala

- The DAOs in the persistence memory module must be bound as singleton
- Add reference.conf for the persistence memory module
- Update Play version to 2.5.1
- Update Scala version to 2.11.8

Release 4.0.0-BEAT4

---

.travis.yml

Fixes #xxxx
What does this PR do?
Why did you take this approach?
Are there any relevant issues / PRs / mailing lists discussions?
Handles bash separators etc. correctly.

Use `-delete` instead of `| xargs rm`

---

silhouette/app/com/mohiva/play/silhouette/impl/providers/oauth2/GitLabProvider.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth2/GitLabProviderSpec.scala
silhouette/test/resources/providers/oauth2/gitlab.access.token.json
silhouette/test/resources/providers/oauth2/gitlab.error.json
silhouette/test/resources/providers/oauth2/gitlab.success.json

This PR adds the GitLab provider along with tests
In order to stay consistent with the rest of the code, I copied the Github Provider and made changes to use Gitlab instead.
* [Gitlab API - OAuth 2](https://gitlab.com/help/api/oauth2.md)
* [Gitlab API - Users](https://gitlab.com/help/api/users.md)

Adding Gitlab Provider

---

project/plugins.sbt

Fixes #xxxx
What does this PR do?
Why did you take this approach?
Are there any relevant issues / PRs / mailing lists discussions?

API docs is not published

---

silhouette-testkit/app/com/mohiva/play/silhouette/test/Fakes.scala
silhouette/app/com/mohiva/play/silhouette/impl/authenticators/CookieAuthenticator.scala
silhouette/test/com/mohiva/play/silhouette/impl/authenticators/CookieAuthenticatorSpec.scala

Change parameter order for the CookieAuthenticator

---

.travis.yml
project/BuildSettings.scala
project/plugins.sbt
scripts/ci-build
scripts/reformat
silhouette/app/com/mohiva/play/silhouette/api/exceptions/CryptoException.scala
silhouette/app/com/mohiva/play/silhouette/impl/authenticators/CookieAuthenticator.scala
silhouette/app/com/mohiva/play/silhouette/impl/daos/AuthenticatorDAO.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/oauth1/secrets/CookieSecret.scala
silhouette/app/com/mohiva/play/silhouette/impl/providers/oauth2/state/CookieState.scala
silhouette/app/com/mohiva/play/silhouette/impl/util/CookieSigner.scala
silhouette/test/com/mohiva/play/silhouette/impl/authenticators/CookieAuthenticatorSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth1/secrets/CookieSecretSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth2/state/CookieStateSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/util/CookieSignerSpec.scala

Cookies are currently not signed, which allows an attacker arbitrarily modifying the cookie value.

Sign cookies with HMAC

---

.travis.yml
CHANGELOG.md
project/plugins.sbt
scripts/ci-build

Code coverage gets not published to Coveralls and other small changes

---

project/BuildSettings.scala
project/plugins.sbt

Change version to 4.1.0-SNAPSHOT

---

silhouette/app/com/mohiva/play/silhouette/impl/providers/OAuth2Provider.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/OAuth2ProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/custom/FacebookProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth1/LinkedInProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth1/TwitterProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth1/XingProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth2/Auth0ProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth2/ClefProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth2/DropboxProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth2/FacebookProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth2/FoursquareProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth2/GitHubProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth2/GitLabProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth2/GoogleProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth2/InstagramProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth2/LinkedInProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/oauth2/VKProviderSpec.scala

Fixes #xxxx
To make it possible to make authorization requests without "redirect_uri" parameter, which even makes the model compliant with the OAuth2 specification.
What does this PR do?
It makes redirectUri parameter optional while making authorization requests to SocialAuth providers.
Why did you take this approach?
Are there any relevant issues / PRs / mailing lists discussions?
Saheb Motiani @Saheb Nov 13 13:07
http://www.silhouette.rocks/docs/config-oauth2-based-providers
In OAuth2Settings, wouldn't it be good to make the redirectUrl an option isn't of having it as mandatory field?
Right now, this makes it impossible to make an authorization request without this parameter
Christian Kaps @akkie Nov 13 14:21
@SunPj Can you provide a repository which shows the issue?
Christian Kaps …

Making redirectUri of OAuth2Settings/Provider Optional

---

.github/ISSUE_TEMPLATE.md
README.md
project/BuildSettings.scala

Change to new domains

---

silhouette/app/com/mohiva/play/silhouette/impl/providers/SocialStateProvider.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/DefaultSocialStateHandlerSpec.scala

DefaultSocialStateHandler does not encode cookies correctly

---

silhouette-password-bcrypt/src/main/scala/com/mohiva/play/silhouette/password/BCryptSha256PasswordHasher.scala
silhouette-password-bcrypt/src/test/scala/com/mohiva/play/silhouette/password/BCryptSha256PasswordHasherSpec.scala

Implement BCryptSha256PasswordHasher to avoid password truncating issue

---

.travis.yml
project/BuildSettings.scala
project/Dependencies.scala
project/plugins.sbt
silhouette/app/com/mohiva/play/silhouette/impl/providers/PasswordProvider.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/BasicAuthProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/CredentialsProviderSpec.scala

Release version 5.0.3

---

project/BuildSettings.scala
project/plugins.sbt

Fixes #538 
Fixes #538
`play-openid` `2.6.9` included `logback-test.xml` accidentally. https://github.com/playframework/playframework/issues/8124
So play-silhouette should avoid to use this version.
- #538 
- https://discuss.lightbend.com/t/play-2-6-13-released/629/12
- https://github.com/playframework/playframework/issues/8124
- https://github.com/playframework/playframework/issues/8361

Update to Play 2.6.13

---

.travis.yml
README.md
project/BuildSettings.scala
project/Dependencies.scala
project/build-jvm-opts
project/plugins.sbt
silhouette-persistence/src/test/scala/com/mohiva/play/silhouette/persistence/repositories/DelegableAuthInfoRepositorySpec.scala
silhouette-testkit/test/com/mohiva/play/silhouette/test/FakesSpec.scala
silhouette/test/com/mohiva/play/silhouette/api/actions/SecuredActionSpec.scala
silhouette/test/com/mohiva/play/silhouette/api/actions/UnsecuredActionSpec.scala
silhouette/test/com/mohiva/play/silhouette/api/actions/UserAwareActionSpec.scala

Updates Play to version 2.6.19 and Scala to 2.12.6

Release version 5.0.6

---

CHANGELOG.md
project/BuildSettings.scala
project/Dependencies.scala
project/build.properties
project/plugins.sbt
silhouette-cas/build.sbt
silhouette-testkit/build.sbt
silhouette/build.sbt
silhouette/test/com/mohiva/play/silhouette/api/EventBusSpec.scala
silhouette/test/com/mohiva/play/silhouette/api/actions/UnsecuredActionSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/authenticators/BearerTokenAuthenticatorSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/authenticators/CookieAuthenticatorSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/authenticators/JWTAuthenticatorSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/OAuth1ProviderSpec.scala
silhouette/test/com/mohiva/play/silhouette/impl/providers/OpenIDProviderSpec.scala

Update to play 2.7

---

silhouette-persistence/src/main/scala/com/mohiva/play/silhouette/persistence/daos/DelegableAuthInfoDAO.scala
silhouette-persistence/src/main/scala/com/mohiva/play/silhouette/persistence/daos/InMemoryAuthInfoDAO.scala

With this change it would be easier to mix it into other abstract classes.
Fixes: #560

Convert DelegableAuthInfoDAO to a trait
